apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: processing-assembly-oee
  name: processing-assembly-oee
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: processing-assembly-oee
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: processing-assembly-oee
    spec:
      containers:
        - env:
            - name: LIMIT
              value: "67"
          image: gcr.io/clusterekaitz/multipass:processing-assembly-oee
          name: processing-assembly-oee
          ports:
            - containerPort: 6000
          resources: {}
      restartPolicy: Always
status: {}
